#ifndef HTTPIMAGEPROVIDER_GLOBAL_H
#define HTTPIMAGEPROVIDER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(HTTPIMAGEPROVIDER_LIBRARY)
#  define HTTPIMAGEPROVIDER_EXPORT Q_DECL_EXPORT
#else
#  define HTTPIMAGEPROVIDER_EXPORT Q_DECL_IMPORT
#endif

#endif // HTTPIMAGEPROVIDER_GLOBAL_H
